# Generated by Django 3.2.9 on 2023-01-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': ['trip_date'], 'verbose_name': 'Trip', 'verbose_name_plural': 'Trips'},
        ),
        migrations.AddField(
            model_name='trip',
            name='num_seats',
            field=models.IntegerField(default=1, help_text='Number of seats available', verbose_name='Number of seats'),
        ),
    ]
